const path = require('path')

const mode = process.env.WEBPACK_SERVE ? 'development' : 'production'
const target = 'web'
const outputDir = 'dst'
const outputPath = path.resolve(__dirname, outputDir)
const tmpFile = 'tmp.file.js'

module.exports = [
    {
        entry: './src/index.html',
        mode,
        target,
        module: {
            rules: [
                {
                    test: /\.html$/,
                    use: {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]'
                        }
                    }
                }
            ]
        },
        output: {
            path: outputPath,
            filename: tmpFile
        }
    },
    {
        entry: './src/index.tsx',
        mode,
        target,
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    use: 'ts-loader'
                },
                {
                    test: /\.css$/,
                    use: [
                        'style-loader',
                        {
                          loader: 'typings-for-css-modules-loader',
                          options: {
                            modules: true,
                            namedExport: true,
                            banner: '// generated by typings-for-css-modules-loader, edit CSS file instead'
                          }
                        }
                    ]
                }
            ]
        },
        resolve: {
            extensions: [ '.tsx', '.ts', '.js' ]
        },
        output: {
            path: outputPath,
            filename: 'bundle.js'
        }
    }
]
