// generated by typings-for-css-modules-loader, edit CSS file instead
export const container: string;
export const column: string;
export const small: string;
export const spring: string;
export const mindthegap: string;
